import BuilderDocumentationConstructor from './builder.documentation-constructor';
import type { TBuilderOptions } from '../../../types/builder-options/builder-options.type';
import type { TCustomSettings } from '../../../types/builder-custom-settings/custom-settings.type';
import type { TDefaultSettings } from '../../../types/builder-default-settings/default-settings.type';

/**
 * @description
 * The `BuilderDocumentation` class extends `BuilderDocumentationConstructor` and is
 * responsible for generating documentation by combining various sections of documentation provided
 * by the parent class.
 *
 * @class BuilderDocumentation
 * @extends BuilderDocumentationConstructor
 */
export default class BuilderDocumentation extends BuilderDocumentationConstructor {
  /**
   * Creates an instance of `BuilderDocumentation`.
   *
   * @param {TCustomSettings} customSettings - The custom settings for the documentation generator.
   * @param {TDefaultSettings} defaultSettings - The default settings for the documentation generator.
   * @param {TBuilderOptions} options - Additional options for the documentation generator.
   * @constructor
   */
  constructor(
    customSettings: TCustomSettings,
    defaultSettings: TDefaultSettings,
    options: TBuilderOptions,
  ) {
    super(customSettings, defaultSettings, options);
  }

  /**
   * Builds the complete documentation by concatenating various sections of
   * documentation generated by the parent class methods.
   *
   * @method buildDocs
   * @return {string} The complete documentation as a string.
   */
  buildDocs(): string {
    let docs = '';

    // Append H1 section documentation
    docs += super.documentationBuildH1();
    // Append breakpoints section documentation
    docs += super.documentationBuildBreakpoints();
    // Append grid section documentation
    docs += super.documentationBuildGrid();
    // Append themes section documentation
    docs += super.documentationBuildThemes();
    // Append utilities section documentation
    docs += super.documentationBuildUtilities();

    return docs;
  }
}
